name: Deploy Presentismo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        shell: powershell
        run: |
          Write-Host "GitHub Actions funciona correctamente"
          Write-Host "Proyecto descargado:"
          Get-ChildItem