name: Deploy Presentismo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Publicar en SmarterASP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: win8067.site4now.net
          username: greynozo27-001
          password: Malvinas.46
          protocol: ftp
          local-dir: ./Out/
          server-dir: /